properties([pipelineTriggers([githubPush()])])
pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/Dockerimages']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url:'https://github.com/tmarkesic/FakeRESTApiTests.git']]])
                sh "ls -lart ./*"
            }
        }
	stage('Install Dependencies') {
	    steps {
		sh 'npm install'	
	    }	
	}
	stage('Run Test') {
	    steps {
		sh 'npm install -g jasmine'
		sh 'jasmine test/Test.spec.js'
	    }
	}
}
